export default [
  { alliteration: 'Ice intensifies inside igloos',
    targetWord: 'i',
    words:
     [ 'is',
       'I',] },
  { alliteration: 'Jittering jumping jazz',
    targetWord: 'j',
    words: [ 'just', 'jedi', 'jittering', 'jumping', 'jazz' ] },
  { alliteration: 'Killer kitten kaboodle',
    targetWord: 'k',
    words: [ 'kitten', 'killer', 'kaboodle' ] },
  { alliteration: 'Lovely ladies laugh',
    targetWord: 'l',
    words:
     [ 'love',
       'looks',
       'laughs',
       'lot',
       'like',
       'lots',
       'laugh',
       'laying',
       'leaves',
       'lego',
       'lightsabers',
       'lets',
       'let\'s',
       'lovely',
       'ladies' ] },]