export default [
  { alliteration: 'Anne ate an apple',
    targetWord: 'a',
    words:
     [ 'apple',
       'are',
       'a',
       'alpaca',
       'and',
       'ate',
       'around',
       'all',
       'act',
       'at',
       'anne',
       'an' ] },
  { alliteration: 'Big brave bears bellow',
    targetWord: 'b',
    words:
     [ 'baby',
       'ball',
       'barbeque',
       'bear',
       'big',
       'bike',
       'bin',
       'build',
       'blocks',
       'busy',
       'but',
       'blankets',
       'be',
       'berries',
       'belly',
       'beach',
       'beautiful',
       'bouncing',
       'brave',
       'bears',
       'bellow' ] },
  { alliteration: 'Cute cuddly cats',
    targetWord: 'c',
    words:
     [ 'cool',
       'clouds',
       'cat',
       'cute',
       'can',
       'climb',
       'cake',
       'city',
       'cliff',
       'climbing',
       'cooking',
       'cozy',
       'careful',
       'comfy',
       'crunchy',
       'color',
       'could',
       'challenge',
       'creative',
       'cuddly',
       'cats' ] },
  { alliteration: 'Disco dad dances',
    targetWord: 'd',
    words:
     [ 'dog',
       'dad',
       'dad\'s',
       'dinosaur',
       'doll',
       'donut',
       'ducks',
       'day',
       'down',
       'drawings',
       'dessert',
       'disco',
       'dances' ] },
  { alliteration: 'Energetic eels electrify',
    targetWord: 'e',
    words:
     [ 'express', 'eat', 'eating', 'energetic', 'eels', 'electrify' ] },
  { alliteration: 'Fragrent flowers flourish',
    targetWord: 'f',
    words:
     [ 'friend',
       'fun',
       'flowers',
       'funny',
       'furry',
       'follow',
       'fire',
       'fish',
       'feel',
       'for',
       'favorite',
       'found',
       'fast',
       'fragrent',
       'flourish' ] },
  { alliteration: 'Go great grandma go',
    targetWord: 'g',
    words:
     [ 'good',
       'grandma',
       'grandpa',
       'grandparents',
       'grumpy',
       'grow',
       'go',
       'great' ] },
  { alliteration: 'Humans hug happily',
    targetWord: 'h',
    words:
     [ 'happy',
       'has',
       'hard',
       'hand',
       'hold',
       'home',
       'horse',
       'hug',
       'have',
       'house',
       'huge',
       'holloween',
       'high',
       'help',
       'humans',
       'happily' ] },
  { alliteration: 'Ice intensifies inside igloos',
    targetWord: 'i',
    words:
     [ 'is',
       'I',
       'I\'m',
       'in',
       'icecream',
       'ice',
       'intensifies',
       'inside',
       'igloos' ] },
  { alliteration: 'Jittering jumping jazz',
    targetWord: 'j',
    words: [ 'just', 'jedi', 'jittering', 'jumping', 'jazz' ] },
  { alliteration: 'Keen kittens kiss kindly',
    targetWord: 'k',
    words: [ 'keen', 'kittens', 'kiss', 'kindly' ] },
  { alliteration: 'Lovely ladies laugh',
    targetWord: 'l',
    words:
     [ 'love',
       'looks',
       'laughs',
       'lot',
       'like',
       'lots',
       'laugh',
       'laying',
       'leaves',
       'lego',
       'lightsabers',
       'lets',
       'let\'s',
       'lovely',
       'ladies' ] },
  { alliteration: 'My mask makes me merry',
    targetWord: 'm',
    words:
     [ 'my',
       'make',
       'me',
       'mother',
       'many',
       'marker',
       'mask',
       'mom',
       'myself',
       'makes',
       'merry' ] },
  { alliteration: 'No nap needs noise',
    targetWord: 'n',
    words: [ 'need', 'no', 'nap', 'needs', 'noise' ] },
  { alliteration: 'Orange octopi organize',
    targetWord: 'o',
    words: [ 'of', 'out', 'on', 'orange', 'octopi', 'organize' ] },
  { alliteration: 'Party people play',
    targetWord: 'p',
    words:
     [ 'park',
       'princess',
       'play',
       'playing',
       'painting',
       'pancake',
       'panda',
       'pie',
       'pink',
       'pizza',
       'plant',
       'protest',
       'puzzle',
       'party',
       'people' ] },
  { alliteration: 'Quality quilt quest',
    targetWord: 'q',
    words: [ 'quality', 'quilt', 'quest' ] },
  { alliteration: 'Reading really rocks',
    targetWord: 'r',
    words: [ 'reading', 'red', 'ride', 'rocks', 'real', 'really' ] },
  { alliteration: 'Super sunshine smile',
    targetWord: 's',
    words:
     [ 'smell',
       'smile',
       'sheep',
       'so',
       'small',
       'sleeps',
       'smells',
       'scary',
       'swim',
       'stories',
       'sometimes',
       'safe',
       'sad',
       'smart',
       'sand',
       'soft',
       'santa',
       'sewing',
       'shells',
       'sidewalk',
       'slide',
       'stack',
       'sunset',
       'sweep',
       'swings',
       'strong',
       'super',
       'sunshine' ] },
  { alliteration: 'Tall towers tremble',
    targetWord: 't',
    words:
     [ 'the',
       'this',
       'tower',
       'tree',
       'to',
       'throw',
       'trash',
       'things',
       'tastes',
       'today',
       'their',
       'tells',
       'tan',
       'tiger',
       'trains',
       'trampoline',
       'turtle',
       'tall',
       'towers',
       'tremble' ] },
  { alliteration: 'Uncles under umbrellas',
    targetWord: 'u',
    words: [ 'uncles', 'under', 'umbrellas' ] },
  { alliteration: 'Violets vary vastly',
    targetWord: 'v',
    words: [ 'very', 'vegetables', 'violets', 'vary', 'vastly' ] },
  { alliteration: 'We wouldn\'t want water wetting whatever',
    targetWord: 'w',
    words:
     [ 'white',
       'when',
       'wool',
       'with',
       'wear',
       'watching',
       'we',
       'went',
       'walk',
       'watch',
       'wouldn\'t',
       'want',
       'water',
       'wetting',
       'whatever' ] },
  { alliteration: 'Your young yak yawns yuckily',
    targetWord: 'y',
    words:
     [ 'yummy', 'you', 'your', 'young', 'yak', 'yawns', 'yuckily' ] },
  { alliteration: 'Zany zebras zigzag',
    targetWord: 'z',
    words: [ 'zany', 'zebras', 'zigzag' ] } ]