export default [
    {sentence: "The dog is my friend", targetWord: "dog", },
    {sentence: "The park is fun", targetWord: "park", },
    {sentence: "Reading is cool", targetWord: "reading", },
    {sentence: "The apple is red", targetWord: "apple", },
    {sentence: "Flowers smell good", targetWord: "flowers", },
    {sentence: "The clouds are white", targetWord: "clouds", },
    {sentence: "This cat is cute", targetWord: "cat", },
    {sentence: "I love my grandma", targetWord: "grandma", },
    {sentence: "I smile when I'm happy", targetWord: "smile", },
    {sentence: "Sheep make wool", targetWord: "sheep", },
    {sentence: "My dad is so cool", targetWord: "dad", },
    {sentence: "A kitten is a small cat", targetWord: "kitten", },
    {sentence: "The princess sleeps in a tower", targetWord: "tower", },
    {sentence: "I can climb a tree", targetWord: "tree", },
    {sentence: "The alpaca looks funny", targetWord: "alpaca", },
    {sentence: "My baby laughs a lot", targetWord: "baby", },
    {sentence: "I like to play with my ball", targetWord: "ball", },
    {sentence: "The barbeque smells good", targetWord: "barbeque", },
    {sentence: "A bear is big and furry", targetWord: "bear", },
    {sentence: "I like to ride my bike", targetWord: "bike", },
    {sentence: "Throw trash in the bin", targetWord: "bin", },
    {sentence: "I build things with my blocks", targetWord: "blocks", },
    {sentence: "Cake tastes yummy", targetWord: "cake", },
    {sentence: "The city is big and busy", targetWord: "city", },
    {sentence: "The cliff has lots of rocks", targetWord: "cliff", },
    {sentence: "Climbing is hard but fun", targetWord: "climbing", },
    {sentence: "My dad's cooking is yummy", targetWord: "cooking", },
    {sentence: "My blankets are so cozy", targetWord: "cozy", },
    {sentence: "The dinosaur is scary", targetWord: "dinosaur", },
    {sentence: "My doll sleeps with me", targetWord: "doll", },
    {sentence: "I ate a donut today", targetWord: "donut", },
    {sentence: "The ducks follow their mother", targetWord: "ducks", },
    {sentence: "Be careful around fire", targetWord: "fire", },
    {sentence: "Fish can swim all day", targetWord: "fish", },
    {sentence: "I love playing with my friend", targetWord: "friend", },
    {sentence: "Grandpa tells fun stories", targetWord: "grandpa", },
    {sentence: "My grandparents love me", targetWord: "grandparents", },
    {sentence: "Sometimes I act out when grumpy", targetWord: "grumpy", },
    {sentence: "My hand can hold so many things", targetWord: "hand", },
    {sentence: "I feel safe at home", targetWord: "home", },
    {sentence: "The horse looks funny", targetWord: "horse", },
    {sentence: "I need a hug when I'm sad", targetWord: "hug", },
    {sentence: "Icecream is very yummy", targetWord: "icecream", },
    {sentence: "Sometimes you just have to laugh", targetWord: "laugh", },
    {sentence: "Laying down is comfy", targetWord: "laying", },
    {sentence: "The leaves are crunchy", targetWord: "leaves", },
    {sentence: "My lego house is huge", targetWord: "lego", },
    {sentence: "Lightsabers are for jedi", targetWord: "lightsabers", },
    {sentence: "I color my drawings with marker", targetWord: "marker", },
    {sentence: "I wear a mask on Holloween", targetWord: "mask", },
    {sentence: "My mom is smart", targetWord: "mom", },
    {sentence: "Painting lets me express myself", targetWord: "painting", },
    {sentence: "I like my pancake with berries", targetWord: "pancake", },
    {sentence: "The furry panda is cute", targetWord: "panda", },
    {sentence: "Pie is my favorite dessert", targetWord: "pie", },
    {sentence: "Pink is my favorite color", targetWord: "pink", },
    {sentence: "I could eat pizza all day", targetWord: "pizza", },
    {sentence: "I like watching my plant grow big", targetWord: "plant", },
    {sentence: "We went to a protest today", targetWord: "protest", },
    {sentence: "This puzzle is a real challenge", targetWord: "puzzle", },
    {sentence: "Sand is soft and tan", targetWord: "sand", },
    {sentence: "Santa has a big belly", targetWord: "santa", },
    {sentence: "Sewing is creative", targetWord: "sewing", },
    {sentence: "Shells are found at the beach", targetWord: "shells", },
    {sentence: "Let's walk on the sidewalk", targetWord: "sidewalk", },
    {sentence: "I slide down fast", targetWord: "slide", },
    {sentence: "I can stack things high", targetWord: "stack", },
    {sentence: "The sunset is beautiful today", targetWord: "sunset", },
    {sentence: "I can sweep to help out", targetWord: "sweep", },
    {sentence: "I like the swings at the park", targetWord: "swings", },
    {sentence: "Watch out for the tiger", targetWord: "tiger", },
    {sentence: "The trains go fast", targetWord: "trains", },
    {sentence: "Bouncing on the trampoline is fun", targetWord: "trampoline", },
    {sentence: "My turtle can swim", targetWord: "turtle", },
    {sentence: "Eating vegetables makes me strong", targetWord: "vegetables", },
]